### ISSUE TITLE
Replace font awesome icons 4 with react-icons / fa5

### ISSUE THREAD

**Issue by mikelax** [mikelax/spacebot-site#3]
# Overview

Currently the site is using font awesome version 4.7. 
This should be updated to use version 5, and switch the icons to the corresponding icon in version 5. 

A possible solution would be to use [react-icons](https://github.com/react-icons/react-icons).

**Comment by yatri1609** [comment]
Can I work on this issue?

**Comment by mikelax** [comment]
Sure, happy to take a look at a PR when ready! 
🚀
